name: Java CI with Maven

env:
  DB_URI: 'mongodb://localhost:27017'
  DB_NAME: 'test'

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # For tests
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '7.0'
    - name: Create maven settings
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: '[{"id": "github", "username": "${{ secrets.SERVER_USERNAME }}", "password": "${{ secrets.SERVER_PASSWORD }}"}]'
    - name: Build app
      run: mvn clean install
